# Generated by Django 5.2 on 2025-05-21 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="fullscreen",
            field=models.BooleanField(default=True),
        ),
    ]
