# Generated by Django 5.2 on 2025-05-21 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_article_fullscreen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="fullscreen",
            field=models.BooleanField(default=False),
        ),
    ]
