# Generated by Django 5.2 on 2025-05-21 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_alter_article_fullscreen"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="multilang",
            field=models.BooleanField(default=False),
        ),
    ]
