# Generated by Django 5.2 on 2025-05-22 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0004_article_multilang"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="content_en",
            field=models.TextField(default=""),
        ),
    ]
