# Generated by Django 5.2 on 2025-05-22 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0005_article_content_en"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="featured_image",
        ),
    ]
